import { colOf, GameState, homeRows, opponent, Piece, PieceKind, Player, rowOf, Square } from './types';
const types: PieceKind[] = ['king', 'knight', 'knight', 'pawn', 'pawn'];
export function startingPieces(): Piece[] { return (['amber', 'violet'] as Player[]).flatMap((owner) => { const squares = owner === 'amber' ? [24, 25, 26, 27, 28] : [6, 7, 8, 9, 10]; return types.map((kind, index) => ({ id: `${owner}-${index}`, owner, kind, square: squares[index], captured: false })); }); }
export function initialGame(): GameState { return { phase: 'setup', turn: 'amber', viewer: 'amber', pieces: startingPieces(), ready: { amber: false, violet: false }, observed: [], feedback: [], selected: null }; }
export function ownPieceAt(state: GameState, player: Player, square: Square) { return state.pieces.find((piece) => !piece.captured && piece.owner === player && piece.square === square); }
export function pieceAt(state: GameState, square: Square) { return state.pieces.find((piece) => !piece.captured && piece.square === square); }
export function validSetupMove(state: GameState, player: Player, from: Square, to: Square) { return !state.ready[player] && homeRows(player).includes(rowOf(to)) && !ownPieceAt(state, player, to) && Boolean(ownPieceAt(state, player, from)); }
export function legalMove(piece: Piece, destination: Square, target?: Piece): boolean { if (destination < 0 || destination > 35) return false; const dx = Math.abs(colOf(destination) - colOf(piece.square)); const dy = rowOf(destination) - rowOf(piece.square); if (piece.kind === 'king') return Math.max(dx, Math.abs(dy)) === 1; if (piece.kind === 'knight') return (dx === 1 && Math.abs(dy) === 2) || (dx === 2 && Math.abs(dy) === 1); const direction = piece.owner === 'amber' ? -1 : 1; return target ? dx === 1 && dy === direction : dx === 0 && dy === direction; }
function attacks(piece: Piece, square: Square, state: GameState) { return legalMove(piece, square, pieceAt(state, square)); }
function tokenFor(piece: Piece) { return { id: piece.id, owner: piece.owner, square: piece.square }; }
function upsertToken(tokens: GameState['observed'], piece: Piece) { const index = tokens.findIndex((token) => token.id === piece.id); const token = tokenFor(piece); return index === -1 ? [...tokens, token] : tokens.map((value, i) => i === index ? token : value); }
export function submitLocalMove(state: GameState, from: Square, to: Square): GameState { const mover = ownPieceAt(state, state.turn, from); const target = pieceAt(state, to); if (!mover || (target && target.owner === mover.owner) || !legalMove(mover, to, target)) return { ...state, selected: null, feedback: [{ kind: 'illegal', text: 'Illegal move, try again.' }, ...state.feedback] }; const moved = { ...mover, square: to }; let pieces = state.pieces.map((piece) => piece.id === moved.id ? moved : piece); let observed = upsertToken(state.observed, moved); let feedback: GameState['feedback']; let phase: GameState['phase'] = 'play'; if (target) { pieces = pieces.map((piece) => piece.id === target.id ? { ...piece, captured: true } : piece); observed = observed.filter((token) => token.id !== target.id); if (target.kind === 'king') { feedback = [{ kind: 'win', text: `${mover.owner === 'amber' ? 'Amber' : 'Violet'} captured the king. Game over.` }, ...state.feedback]; phase = 'over'; } else feedback = [{ kind: 'capture', text: `Legal capture: ${target.kind} revealed on the captured square.`, captured: target.kind, square: to }, ...state.feedback]; } else feedback = [{ kind: 'quiet', text: 'Legal move, no capture.' }, ...state.feedback]; const next: GameState = { ...state, pieces, observed, feedback, phase, selected: null, turn: phase === 'over' ? state.turn : opponent(state.turn) }; const enemyKing = next.pieces.find((piece) => piece.owner === next.turn && piece.kind === 'king' && !piece.captured); const checkingPiece = enemyKing && next.pieces.find((piece) => piece.owner === mover.owner && !piece.captured && attacks(piece, enemyKing.square, next)); return checkingPiece && phase !== 'over' ? { ...next, feedback: [{ kind: 'check', text: 'Check.' }, ...next.feedback] } : next; }
